[package]
name = "drill"
version = "0.1.0"
edition = "2021"
description = "The Metal installer. The equivalent to rustup."

[dependencies]
tapcli = { workspace = true }
thiserror = { workspace = true }
colored = {workspace = true}

[lints]
workspace = true