---
updates:
  - commit-message:
      prefix: deps
    directory: /
    groups:
      cargo:
        applies-to: version-updates
        patterns:
          - '*'
    labels:
      - 'a: deps'
    package-ecosystem: cargo
    reviewers:
      - elenakrittik
      - VincentRPS
    schedule:
      interval: weekly
      time: '07:00'
version: 2