use proc_macro2::TokenStream;
use quote::quote;

/// Creates a [syn::Ident] from a [String].
pub fn call_site_ident(ident: impl AsRef<str>) -> syn::Ident {
    syn::Ident::new(ident.as_ref(), proc_macro2::Span::call_site())
}

pub fn save_generated(tokens: TokenStream, to: &str) -> Result<(), crate::Error> {
    let tokens = quote! {
        //! This file is @generated by the build script, do not edit by hand.

        #tokens
    }
    .to_string();

    let parsed = syn::parse_file(&tokens)?;
    let formatted = prettyplease::unparse(&parsed);

    std::fs::write(to, formatted)?;

    Ok(())
}
