use proc_macro2::TokenStream;
use quote::quote;

pub fn save_generated(tokens: TokenStream, to: &str) -> Result<(), crate::Error> {
    let tokens = quote! {
        //! This file is @generated by the build script, do not edit by hand.

        #tokens
    }
    .to_string();

    let parsed = syn::parse_file(&tokens)?;
    let formatted = prettyplease::unparse(&parsed);

    std::fs::write(to, formatted)?;

    Ok(())
}
