[package]
name = "metal-lexer-ng"
version = "0.1.0"
edition = "2024"

[dependencies]
metal-proc-macros = { workspace = true }

[build-dependencies]
metal-ungram = { workspace = true }

[lints]
workspace = true
