[package]
name = "metal-parser"
version = "0.1.0"
edition = "2021"
description = "The Metal language parser."

[dependencies]
peekable = { workspace = true }
metal-lexer = { workspace = true }
metal-ast = { workspace = true }
