[package]
name = "metal-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan = { workspace = true }
metal-lexer = { workspace = true }
metal-ast = { workspace = true }

[lints]
workspace = true
