// SPDX-License-Identifier: MIT

//! This file is @generated by the build script, do not edit by hand.
/// The kind of a token.
pub enum TokenKind {
    /// Represents the `{` token.
    LBrace,
    /// Represents the `}` token.
    RBrace,
    /// Represents the `@ident` token.
    LitIdent,
    /// Represents the `pub` token.
    Pub,
    /// Represents the `mut` token.
    Mut,
    /// Represents the `=` token.
    Eq,
    /// Represents the `:` token.
    Colon,
    /// Represents the `abstract` token.
    Abstract,
    /// Represents the `def` token.
    Def,
    /// Represents the `;` token.
    Semicolon,
    /// Represents the `const` token.
    Const,
    /// Represents the `enum` token.
    Enum,
    /// Represents the `(` token.
    LParen,
    /// Represents the `)` token.
    RParen,
    /// Represents the `,` token.
    Comma,
    /// Represents the `import` token.
    Import,
    /// Represents the `.` token.
    Dot,
    /// Represents the `return` token.
    Return,
    /// Represents the `struct` token.
    Struct,
    /// Represents the `type` token.
    Type,
    /// Represents the `[` token.
    LBracket,
    /// Represents the `]` token.
    RBracket,
    /// Represents the `&` token.
    Amp,
    /// Represents the `+` token.
    Plus,
    /// Represents the `-` token.
    Minus,
    /// Represents the `!` token.
    Bang,
    /// Represents the `~` token.
    Tilde,
    /// Represents the `+=` token.
    PlusEq,
    /// Represents the `-=` token.
    MinusEq,
    /// Represents the `/=` token.
    SlashEq,
    /// Represents the `*=` token.
    StarEq,
    /// Represents the `**=` token.
    Star2Eq,
    /// Represents the `%=` token.
    PercentEq,
    /// Represents the `^=` token.
    CaretEq,
    /// Represents the `&=` token.
    AmpEq,
    /// Represents the `|=` token.
    PipeEq,
    /// Represents the `<<=` token.
    ShiftlEq,
    /// Represents the `>>=` token.
    ShiftrEq,
    /// Represents the `/` token.
    Slash,
    /// Represents the `*` token.
    Star,
    /// Represents the `**` token.
    Star2,
    /// Represents the `%` token.
    Percent,
    /// Represents the `&&` token.
    Amp2,
    /// Represents the `||` token.
    Pipe2,
    /// Represents the `==` token.
    Eq2,
    /// Represents the `!=` token.
    BangEq,
    /// Represents the `>` token.
    Gt,
    /// Represents the `>=` token.
    GtEq,
    /// Represents the `<` token.
    Lt,
    /// Represents the `<=` token.
    LtEq,
    /// Represents the `^` token.
    Caret,
    /// Represents the `|` token.
    Pipe,
    /// Represents the `<<` token.
    Lt2,
    /// Represents the `>>` token.
    Gt2,
    /// Represents the `..` token.
    Dot2,
    /// Represents the `@number` token.
    LitNum,
    /// Represents the `@string` token.
    LitStr,
    /// A special token representing an unknown token.
    Unknown,
    /// A special token representing the end of an input.
    EndOfFile,
}
