name: Check if paths have changed
description: .
inputs:
  globs:
    description: The paths to check for changes
    required: true

outputs:
  have_changed:
    description: Whether the probed paths have changed
    value: ${{ steps.check.outputs.have_changed }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - id: check
      run: |
        import re
        from os import environ as env
        from subprocess import check_output

        changed_files = check_output(["git", "diff", "--name-only", "HEAD~1..HEAD"]).decode("utf-8").splitlines()
        globs = [glob.replace(".", "\\.").replace("**", ".*").replace("*", ".*").replace("..*", ".*") for glob in (${{ inputs.globs }}).splitlines()]
        yes = False

        for glob in globs:
          regex = re.compile(glob)

          for changed_file in changed_files:
            if regex.search(changed_file):
              yes = True
              break
          
          if yes:
            break
        
        env["GITHUB_OUTPUT"] = "yes" if yes else "no"
      shell: python
