# SPDX-License-Identifier: MIT

name: Clippy

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.head_ref || github.ref_name }}
  cancel-in-progress: false # The day will come, and this will be true

jobs:
  clippy:
    strategy:
      matrix:
        target:
          - id: "linux-amd64"
            os: "ubuntu-latest"
          - id: "darwin-aarch64"
            os: "macos-latest"
          - id: "darwin-amd64"
            os: "macos-13"
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-llvm
      - uses: rui314/setup-mold@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-11-17
          components: clippy

      - run: cargo clippy
