---
concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.head_ref && github.head_ref || github.ref_name }}
jobs:
  clippy:
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-llvm
      - uses: rui314/setup-mold@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          toolchain: nightly-2024-12-15
      - run: cargo clippy
    strategy:
      matrix:
        target:
          - id: linux-amd64
            os: ubuntu-latest
          - id: darwin-aarch64
            os: macos-latest
          - id: darwin-amd64
            os: macos-13
name: Clippy
'on':
  push: null
  workflow_dispatch: null# SPDX-License-Identifier: MIT
