# SPDX-License-Identifier: MIT

name: License headers

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.head_ref || github.ref_name }}
  cancel-in-progress: false # The day will come, and this will be true

jobs:
  license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-shear

      - shell: bash
        run: |
          shopt -s extglob

          RED='\033[0;31m' # red color
          NC='\033[0m' # no color aka color reset
          EXCLUDE_PATTERN='+(LICENSE|*.toml|mir-tests/*|README.md|.gitignore|.github/dependabot.yml|.gitattributes)'
          HEADER='SPDX-License-Identifier: MIT'
          FAILURE=false
          FILES=$(git ls-files)

          for filename in $FILES; do
            if [[ "$filename" == $EXCLUDE_PATTERN ]]; then
              echo "Skipping $filename because it was manually exempted from the check"
              continue
            fi

            FILE_HEAD=$(head $filename)

            # grep returns 1 (failure) if it doesn't find a match
            if ! (echo "$FILE_HEAD" | grep -q "$HEADER"); then
              echo -e "${RED}File $filename does not have an SPDX license header${NC}"
              FAILURE=true
            fi
          done

          if [ "$FAILURE" = true ]; then
            exit 1
          fi
