# SPDX-License-Identifier: MIT

name: License headers

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.head_ref || github.ref_name }}
  cancel-in-progress: false # The day will come, and this will be true

jobs:
  license-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-shear

      - shell: bash
        run: |
          shopt -s extglob
          EXCLUDE_PATTERN='WONTMATCHTESTESTEST'
          HEADER='SPDX-License-Identifier: MIT'
          FAILURE=false

          for filename in **/*; do
            case filename in
              $EXCLUDE_PATTERN) echo "Skipping $filename" ;;
              *) : ;;
            esac

            FILE_HEAD=(head $filename)
            echo "$FILE_HEAD" | grep $HEADER

            # grep returns 1 (failure) if it doesn't find a match
            if [ $? -eq 1 ]; then
              echo "File $filename does not have an SPDX license header"
              FAILURE=true
            fi
          done
          
          if [ "$FAILURE" = true ]; then
            exit 1
          fi
